export const abbreviations = {
  Aba: "WAT",
  Abadan: "",
  Abeokuta: "WAT",
  Abidjan: "GMT",
  Abobo: "GMT",
  "Abomey-Calavi": "WAT",
  "Abu Dhabi": "",
  "Abu Ghraib": "",
  Abuja: "WAT",
  "Acapulco de Juarez": "CST",
  Accra: "GMT",
  "Ad Dammam": "",
  Adamstown: "",
  Adana: "",
  "Addis Abeba": "EAT",
  Adelaide: "ACDT",
  Afghanistan: "",
  Agadir: "",
  Agra: "IST",
  Aguascalientes: "CST",
  Ahmedabad: "IST",
  Ahvaz: "",
  Ajmer: "IST",
  Akola: "IST",
  Akure: "WAT",
  Bàssora: "",
  "Al Basrah al Qadimah": "",
  "Al Hudaydah": "",
  Giza: "EET",
  "Al Mahallah al Kubra": "EET",
  "Al Mansurah": "EET",
  "Al Mawsil al Jadidah": "",
  "Al Ubayyid": "CAT",
  "Al-Ayn": "",
  Birmingham: "CST",
  "Isole Åland": "EET",
  Anchorage: "AKST",
  Albania: "CET",
  Albuquerque: "MST",
  Aleppo: "EET",
  "Alessandria d'Egitto": "EET",
  Algeria: "CET",
  Algeri: "CET",
  Aligarh: "IST",
  Allahabad: "IST",
  Almaty: "",
  Alofi: "",
  Amagasaki: "JST",
  "Samoa Americane": "SST",
  Amman: "EET",
  Amravati: "IST",
  Amritsar: "IST",
  Amsterdam: "CET",
  Najaf: "",
  Nasiriya: "",
  Ananindeua: "",
  Andorra: "CET",
  "Andorra la Vella": "CET",
  Angola: "WAT",
  Anguilla: "AST",
  Ankara: "",
  Ansan: "KST",
  Anshan: "CST",
  Adalia: "",
  Antananarivo: "EAT",
  Antartide: "NZDT",
  "Antigua e Barbuda": "AST",
  Antipolo: "PST",
  Anversa: "CET",
  Macao: "CST",
  Apia: "",
  Aracaju: "",
  Arak: "",
  Arbil: "",
  Ardabil: "",
  Arequipa: "",
  Argentina: "",
  Phoenix: "MST",
  "Little Rock": "CST",
  Armenia: "",
  Aruba: "AST",
  "As Sulaymaniyah": "",
  Asansol: "IST",
  Aşgabat: "",
  Asmara: "EAT",
  "Nur-Sultan": "",
  "Astrachan'": "",
  Asunción: "",
  Asyut: "EET",
  "At Ta'if": "",
  Atene: "EET",
  Atlanta: "EST",
  Auckland: "NZDT",
  Aurangabad: "IST",
  Austin: "CST",
  Austria: "CET",
  Avarua: "",
  "Az Zarqa'": "EET",
  Azadshahr: "",
  Azerbaigian: "",
  Baghdad: "",
  Bahamas: "EST",
  Bahawalpur: "PKT",
  Bahrain: "",
  "Tarawa Sud": "",
  Baku: "",
  Bali: "WITA",
  Balikpapan: "WITA",
  Baltimora: "EST",
  Bamako: "GMT",
  Bamenda: "WAT",
  "Bandar Seri Begawan": "",
  Bandung: "WIB",
  Bengasi: "EET",
  Bangkok: "",
  Bangladesh: "",
  Bangui: "WAT",
  Banjarmasin: "WITA",
  Banjul: "GMT",
  "Prefettura di Baoding": "CST",
  Baotou: "CST",
  Barbados: "AST",
  Barcelona: "CET",
  Bareilly: "IST",
  Barnaul: "",
  Barquisimeto: "",
  Barranquilla: "",
  "Basse-Terre": "AST",
  Basseterre: "AST",
  Pechino: "CST",
  Beira: "CAT",
  Beirut: "EET",
  Bekasi: "WIB",
  Bielorussia: "",
  Belém: "",
  "Belford Roxo": "",
  Belgaum: "IST",
  Belgio: "CET",
  Belgrado: "CET",
  Belize: "CST",
  Bello: "",
  Belmopan: "CST",
  "Belo Horizonte": "",
  Varanasi: "IST",
  Bangalore: "IST",
  Bengbu: "CST",
  Benin: "WAT",
  "Benin City": "WAT",
  Benoni: "SAST",
  Benxi: "CST",
  Berlino: "CET",
  Bermuda: "AST",
  Berna: "CET",
  Betim: "",
  Bhatpara: "IST",
  Bhavnagar: "IST",
  "Bhilai Nagar": "IST",
  Bhiwandi: "IST",
  Bhopal: "IST",
  Bhubaneshwar: "IST",
  Bhutan: "",
  "Bien Hoa": "",
  Bikaner: "IST",
  Billings: "MST",
  Biškek: "",
  Bissau: "GMT",
  Blantyre: "CAT",
  Bloemfontein: "SAST",
  Bochum: "CET",
  "Bochum-Hordel": "CET",
  Bogor: "WIB",
  Bogotá: "",
  Bokaro: "IST",
  Boksburg: "SAST",
  Bolivia: "",
  Bologna: "CET",
  "Bosnia ed Erzegovina": "CET",
  Boston: "EST",
  Botswana: "CAT",
  Bouake: "GMT",
  Boumerdas: "CET",
  "Isola Bouvet": "CET",
  Brasília: "",
  Bratislava: "CET",
  "Brazil - Sao Paulo": "",
  Brazzaville: "WAT",
  Brema: "CET",
  Bridgetown: "AST",
  Brisbane: "AEST",
  Bristol: "GMT",
  "Territorio Britannico dell’Oceano Indiano": "",
  "Isole Vergini Britanniche": "AST",
  Brooklyn: "EST",
  Brunei: "",
  Bruxelles: "CET",
  Brjansk: "MSK",
  Bucaramanga: "",
  Bucarest: "EET",
  Budapest: "CET",
  "Buenos Aires": "",
  Bujumbura: "CAT",
  Bulawayo: "CAT",
  Bulgaria: "EET",
  "Bur Sa`id": "EET",
  Buraydah: "",
  "Burkina Faso": "GMT",
  Burlington: "EST",
  Bursa: "",
  Burundi: "CAT",
  "Cagayan de Oro": "PST",
  "Il Cairo": "EET",
  Calabar: "WAT",
  Calcutta: "IST",
  Calgary: "MST",
  Cali: "",
  Calicut: "IST",
  "San Francisco": "PST",
  Callao: "",
  Camayenne: "GMT",
  Cambogia: "",
  Camerun: "WAT",
  Campinas: "",
  "Campo Grande": "",
  Campos: "",
  "Canada - Calgary": "MST",
  "Canada - Edmonton": "MST",
  "Canada - Halifax": "AST",
  "Canada - Montreal": "EST",
  "Canada - Newfoundland": "NST",
  "Canada - Quebec": "EST",
  "Canada - Toronto": "EST",
  "Canada - Vancouver": "PST",
  "Canada - Winnipeg": "CST",
  Canberra: "AEDT",
  Cancún: "EST",
  Cangzhou: "CST",
  Cankaya: "",
  "Città del Capo": "SAST",
  "Capo Verde": "",
  Caracas: "",
  Carrefour: "EST",
  "Cartagena de Indias": "",
  Casablanca: "",
  Castries: "AST",
  "Caxias do Sul": "",
  Caienna: "",
  "Isole Cayman": "EST",
  "Cebu City": "PST",
  "Repubblica Centrafricana": "WAT",
  "Ch'angwon": "KST",
  "Ch'ongju": "KST",
  Ciad: "WAT",
  Chandigarh: "IST",
  Changchun: "CST",
  Changde: "CST",
  Changsha: "CST",
  Changzhi: "CST",
  Changzhou: "CST",
  Chaoyang: "CST",
  Chaozhou: "CST",
  Charleston: "EST",
  Charlotte: "EST",
  Charlottetown: "AST",
  Čeboksary: "MSK",
  Jeju: "KST",
  Chelyabinsk: "",
  Chengde: "CST",
  Chengdu: "CST",
  Chennai: "IST",
  Cheyenne: "MST",
  "Chi-lung": "CST",
  Chiba: "JST",
  Chiclayo: "",
  Chihuahua: "MST",
  Cile: "",
  Cina: "CST",
  Chişinău: "EET",
  Chittagong: "",
  Chongqing: "CST",
  Chonju: "KST",
  Christchurch: "NZDT",
  "Isola di Christmas": "",
  Cimahi: "WIB",
  "Ciudad Guayana": "",
  "Ciudad Juárez": "MST",
  "Ciudad Lopez Mateos": "CST",
  "Ciudad Nezahualcoyotl": "CST",
  Cleveland: "EST",
  Cochabamba: "",
  Cochin: "IST",
  "Isole Cocos": "",
  Coimbatore: "IST",
  Colombia: "",
  Colombo: "",
  Denver: "MST",
  Columbia: "EST",
  Columbus: "EST",
  Comilla: "",
  Comore: "EAT",
  Conakry: "GMT",
  "Congo - Kinshasa": "WAT",
  "Congo - Lubumbashi": "CAT",
  Bridgeport: "EST",
  Constantina: "CET",
  Contagem: "",
  "Isole Cook": "",
  Copenaghen: "CET",
  Córdoba: "",
  "Costa Rica": "CST",
  Cotonou: "WAT",
  Croazia: "CET",
  "Cuautitlan Izcalli": "CST",
  Cuba: "CST",
  Cucuta: "",
  Cuiabá: "",
  Culiacan: "MST",
  Curitiba: "",
  Cuttack: "IST",
  Cipro: "EET",
  Cechia: "CET",
  "Da Nang": "",
  Dakar: "GMT",
  Dalian: "CST",
  Dallas: "CST",
  Damasco: "EET",
  Dandong: "CST",
  "Dar es Salaam": "EAT",
  Darwin: "ACST",
  Dasmarinas: "PST",
  Datong: "CST",
  Davao: "PST",
  Dayan: "CST",
  "Dehra Dun": "IST",
  Delaware: "EST",
  Delhi: "IST",
  "Delmas 73": "EST",
  "Repubblica Democratica del Congo": "CAT",
  "L'Aia": "CET",
  Danimarca: "CET",
  Denpasar: "WITA",
  Depok: "WIB",
  "Des Moines": "CST",
  Detroit: "EST",
  Dezhou: "CST",
  Dacca: "",
  Diadema: "",
  "Diego Garcia": "",
  Dili: "",
  Diyarbakir: "",
  Gibuti: "EAT",
  "Dnipropetrovs'k": "EET",
  Dodoma: "EAT",
  Doha: "",
  Dominica: "AST",
  "Repubblica Dominicana": "AST",
  "Donec'k": "EET",
  Dongguan: "CST",
  Dortmund: "CET",
  Douala: "WAT",
  Douglas: "GMT",
  Dresda: "CET",
  Dubai: "",
  Dublino: "GMT",
  Duisburg: "CET",
  "Duque de Caxias": "",
  Durango: "CST",
  Durban: "SAST",
  Durgapur: "IST",
  Dušhanbe: "",
  Düsseldorf: "CET",
  "Timor Est": "",
  Ecatepec: "CST",
  Ecuador: "",
  Edimburgo: "GMT",
  Edmonton: "MST",
  Egitto: "EET",
  "El Paso": "MST",
  "El Salvador": "CST",
  England: "GMT",
  Enugu: "WAT",
  "Guinea Equatoriale": "WAT",
  Eritrea: "EAT",
  Erzurum: "",
  Esfahan: "",
  Eskisehir: "",
  Essen: "CET",
  Estonia: "EET",
  Etiopia: "EAT",
  Faisalabad: "PKT",
  "Isole Falkland": "",
  Fargo: "CST",
  Faridabad: "IST",
  "Isole Faroe": "WET",
  "Feira de Santana": "",
  Fez: "",
  Figi: "",
  Finlandia: "EET",
  Firenze: "CET",
  Florianópolis: "",
  "Florida - Pensacola": "CST",
  "The Settlement": "",
  "Fort Worth": "CST",
  "Fort-de-France": "AST",
  Fortaleza: "",
  Foshan: "CST",
  Francia: "CET",
  "Francoforte sul Meno": "CET",
  Fredericton: "AST",
  Freetown: "GMT",
  "Guiana Francese": "",
  "French Polynesia": "",
  "Terre australi e antartiche francesi": "",
  Fresno: "PST",
  Fujisawa: "JST",
  Fukuoka: "JST",
  Fukuyama: "JST",
  Funabashi: "JST",
  Funafuti: "",
  Fushun: "CST",
  Fuxin: "CST",
  Fuzhou: "CST",
  Gabon: "WAT",
  Gaborone: "CAT",
  Gambia: "GMT",
  Garoua: "WAT",
  Gaya: "IST",
  Gaza: "EET",
  Gaziantep: "",
  Danzica: "CET",
  Genova: "CET",
  "George Town": "EST",
  Georgetown: "",
  "Georgia (Country)": "",
  "Georgia - United States": "EST",
  Germania: "CET",
  Ghana: "GMT",
  Ghaziabad: "IST",
  Gibilterra: "CET",
  Gifu: "JST",
  Glasgow: "GMT",
  Göteborg: "CET",
  Goiânia: "",
  "Gold Coast": "AEST",
  "Grand Dakar": "GMT",
  "Grand Turk": "EST",
  "Great Britain": "GMT",
  Grecia: "EET",
  "Greenland - Nuuk": "",
  Grenada: "AST",
  Grytviken: "",
  Guadalajara: "CST",
  Guadalupe: "CST",
  Guadalupa: "AST",
  Guam: "ChST",
  Canton: "CST",
  Guarulhos: "",
  Guatemala: "CST",
  "Città del Guatemala": "CST",
  Guayaquil: "",
  Guernsey: "GMT",
  Guilin: "CST",
  Guinea: "GMT",
  "Guinea-Bissau": "GMT",
  Guiyang: "CST",
  Gujranwala: "PKT",
  Gulbarga: "IST",
  Guli: "CST",
  Guntur: "IST",
  Gustavia: "AST",
  Guwahati: "IST",
  Guyana: "",
  Gwalior: "IST",
  Hanoi: "",
  Hachiōji: "JST",
  Hagåtña: "ChST",
  Haikou: "CST",
  Haiphong: "",
  Haiti: "EST",
  Halifax: "AST",
  Hamadan: "",
  Hama: "EET",
  Hamamatsu: "JST",
  Amburgo: "CET",
  Hamhung: "KST",
  Hamilton: "EST",
  Handan: "CST",
  Hangzhou: "CST",
  Hannover: "CET",
  Haora: "IST",
  Harare: "CAT",
  Harbin: "CST",
  Hargeysa: "EAT",
  "L'Avana": "CST",
  Honolulu: "HST",
  "Isole Heard e McDonald": "AWST",
  Hefei: "CST",
  Hegang: "CST",
  Helsinki: "EET",
  Hengshui: "CST",
  Hengyang: "CST",
  Hermosillo: "MST",
  Himeji: "JST",
  Homs: "EET",
  Hirakata: "JST",
  Hiroshima: "JST",
  Hobart: "AEDT",
  Hohhot: "CST",
  "Homel'": "",
  Honduras: "CST",
  "Hong Kong": "HKT",
  Honiara: "",
  Houston: "CST",
  "Hsin-chu-shih": "CST",
  Huaibei: "CST",
  Huainan: "CST",
  Huaiyin: "CST",
  Huancayo: "",
  Huangshi: "CST",
  Hubli: "IST",
  Ungheria: "CET",
  Ibadan: "WAT",
  Ibague: "",
  Islanda: "GMT",
  Ichikawa: "JST",
  Boise: "MST",
  Chicago: "CST",
  Iloilo: "PST",
  Ilorin: "WAT",
  "Inch'on": "KST",
  India: "IST",
  "Indiana - Indianapolis": "EST",
  Indianapolis: "EST",
  Indonesia: "WITA",
  Indore: "IST",
  Ipoh: "",
  Iqaluit: "EST",
  Iquitos: "",
  Iran: "",
  Iraq: "",
  Irlanda: "GMT",
  Irkutsk: "",
  Islamabad: "PKT",
  "Isola di Man": "GMT",
  Israele: "IST",
  Istanbul: "",
  Italia: "CET",
  Ivanovo: "MSK",
  "Costa d'Avorio": "GMT",
  Iževsk: "",
  Smirne: "",
  Jabalpur: "IST",
  Jaboatao: "",
  "Jaboatao dos Guararapes": "",
  Jackson: "CST",
  Jacksonville: "EST",
  Jaipur: "IST",
  Giacarta: "WIB",
  Jalandhar: "IST",
  "Jalapa Enriquez": "CST",
  Jalgaon: "IST",
  Giamaica: "EST",
  Jambi: "WIB",
  Jamestown: "GMT",
  Jammu: "IST",
  Jamnagar: "IST",
  Jamshedpur: "IST",
  Giappone: "JST",
  Jersey: "GMT",
  Gerusalemme: "IST",
  Jhansi: "IST",
  Jiamusi: "CST",
  Jiangmen: "CST",
  Jiaojiang: "CST",
  Jiaozuo: "CST",
  Jiaxing: "CST",
  Jedda: "",
  Jieyang: "CST",
  Jilin: "CST",
  Jinan: "CST",
  Jining: "CST",
  Jinzhou: "CST",
  Jixi: "CST",
  "Joao Pessoa": "",
  Jodhpur: "IST",
  Johannesburg: "SAST",
  "Johor Bahru": "",
  Joinville: "",
  Giordania: "EET",
  Jos: "WAT",
  "Juan Dolio": "AST",
  "Juiz de Fora": "",
  Kabul: "",
  Kaduna: "WAT",
  Kagoshima: "JST",
  Kahramanmaras: "",
  Kahriz: "",
  "Kai Feng": "CST",
  Kaliningrad: "EET",
  Kalyan: "IST",
  Kampala: "EAT",
  "Kampung Baru Subang": "",
  Kananga: "CAT",
  Kanazawa: "JST",
  Kandahar: "",
  Kano: "WAT",
  Kanpur: "IST",
  "Kansas - Wichita": "CST",
  "Kansas City": "CST",
  "Kao-hsiung": "CST",
  Karachi: "PKT",
  Karagandy: "",
  Karaj: "",
  Kerbela: "",
  Kassala: "CAT",
  Kathmandu: "",
  Katsina: "WAT",
  Kaunas: "EET",
  Kawaguchi: "JST",
  Kawasaki: "JST",
  "Cesarea in Cappadocia": "",
  "Kazakhstan - Almaty": "",
  "Kazan'": "MSK",
  Kemerovo: "",
  "Kentucky - Lexington": "EST",
  "Kentucky - Lexington-Fayette": "EST",
  Louisville: "EST",
  "Kentucky - Owensboro": "CST",
  Kenya: "EAT",
  Kerman: "",
  Kermanshah: "",
  Habarovsk: "",
  "Khabarovsk Vtoroy": "",
  "Khamis Mushayt": "",
  Kharkiv: "EET",
  Khartum: "CAT",
  "Khmel'nyts'kyy": "EET",
  Khulna: "",
  Kiev: "EET",
  Kigali: "CAT",
  Kingston: "EST",
  Kingstown: "AST",
  Kinshasa: "WAT",
  Kirkuk: "",
  Kirov: "",
  Kisangani: "CAT",
  Kitakyushu: "JST",
  Kitchener: "EST",
  Kitwe: "CAT",
  Klang: "",
  Knoxville: "EST",
  Kōbe: "JST",
  Colonia: "CET",
  Kolhapur: "IST",
  Kolwezi: "CAT",
  Iconio: "",
  Korba: "IST",
  Koror: "",
  Kota: "IST",
  "Kota Kinabalu": "",
  Kotli: "PKT",
  Kousseri: "WAT",
  Kowloon: "HKT",
  Cracovia: "CET",
  Krasnodar: "MSK",
  Krasnoyarsk: "",
  Krugersdorp: "SAST",
  "Kryvyj Rih": "EET",
  "Kuala Lumpur": "",
  Kuching: "",
  Kumamoto: "JST",
  Kumasi: "GMT",
  Kunming: "CST",
  Kurashiki: "JST",
  Kursk: "MSK",
  Kuwait: "",
  Kwangju: "KST",
  Kyiv: "EET",
  Kyoto: "JST",
  Kirghizistan: "",
  Leopoli: "EET",
  "La Paz": "",
  "La Plata": "",
  Lagos: "WAT",
  Lahore: "PKT",
  Langfang: "CST",
  Lanzhou: "CST",
  Laos: "",
  "Las Palmas de Gran Canaria": "WET",
  "Las Pavas": "",
  "Las Vegas": "PST",
  Lettonia: "EET",
  Libano: "EET",
  Leeds: "GMT",
  Lipsia: "CET",
  Leon: "CST",
  Lesotho: "SAST",
  Lexington: "EST",
  "Lexington-Fayette": "EST",
  Liaoyang: "CST",
  Liaoyuan: "CST",
  Liberia: "GMT",
  Libreville: "WAT",
  Libia: "EET",
  Liechtenstein: "CET",
  Likasi: "CAT",
  Lilongwe: "CAT",
  Lima: "",
  Lincoln: "CST",
  Lipeck: "MSK",
  Lisbona: "WET",
  Lituania: "EET",
  Liuyang: "CST",
  Liverpool: "GMT",
  Lubiana: "CET",
  Lobamba: "SAST",
  Łódź: "CET",
  Lomé: "GMT",
  Londra: "GMT",
  Londrina: "",
  "Long Beach": "PST",
  Longyearbyen: "CET",
  "Los Angeles": "PST",
  "New Orleans": "CST",
  Luancheng: "CST",
  Luanda: "WAT",
  Lubumbashi: "CAT",
  Lucknow: "IST",
  Ludhiana: "IST",
  "Luhans'k": "EET",
  Luohe: "CST",
  Luoyang: "CST",
  Luqiaozhen: "CST",
  Lusaka: "CAT",
  Lussemburgo: "CET",
  Luxor: "EET",
  Lione: "CET",
  Macedonia: "CET",
  Maceió: "",
  Machida: "JST",
  Madagascar: "EAT",
  Madrid: "CET",
  Madurai: "IST",
  Magnitogorsk: "",
  Maiduguri: "WAT",
  Portland: "EST",
  Majuro: "",
  Makassar: "WITA",
  Machačkala: "MSK",
  Makiyivka: "EET",
  Malabo: "WAT",
  Málaga: "CET",
  Malang: "WIB",
  Malatya: "",
  Malawi: "CAT",
  Malesia: "",
  Maldive: "",
  Malé: "",
  Malegaon: "IST",
  Mali: "GMT",
  Malta: "CET",
  Mamoutzou: "EAT",
  Mamuju: "WITA",
  Manado: "WITA",
  Managua: "CST",
  Manama: "",
  Manaus: "",
  Mandalay: "",
  Mangalore: "IST",
  Manila: "PST",
  Mansilingan: "PST",
  Maputo: "CAT",
  "Mar del Plata": "",
  Maracaibo: "",
  "Mariupol'": "EET",
  Marrakech: "",
  Marsiglia: "CET",
  "Isole Marshall": "",
  Martinica: "AST",
  Maseru: "SAST",
  Mashhad: "",
  Masina: "WAT",
  Matamoros: "CST",
  Matola: "CAT",
  Matsudo: "JST",
  Maturín: "",
  Maua: "",
  Mauritania: "GMT",
  Mauritius: "",
  Mawlamyine: "",
  Mayotte: "EAT",
  Mbabane: "SAST",
  "Mbuji-Mayi": "CAT",
  "La Mecca": "",
  Medan: "WIB",
  Medellín: "",
  Medina: "",
  Meerut: "IST",
  Meknes: "",
  Melbourne: "AEDT",
  Melekeok: "",
  Memphis: "CST",
  Mendoza: "",
  Mersin: "",
  Merida: "CST",
  Mesa: "MST",
  Mexicali: "PST",
  "Mexico - Mexico City": "CST",
  "Città del Messico": "CST",
  Miami: "EST",
  Milano: "CET",
  Milwaukee: "CST",
  Minneapolis: "CST",
  Minsk: "",
  Misratah: "EET",
  Mixco: "CST",
  Mogadiscio: "EAT",
  Moldavia: "EET",
  Mombasa: "EAT",
  Monaco: "CET",
  Mongolia: "",
  Monrovia: "GMT",
  Montana: "MST",
  Montenegro: "CET",
  Monterrey: "CST",
  Montevideo: "",
  Montréal: "EST",
  Montserrat: "AST",
  Moradabad: "IST",
  Morelia: "CST",
  Marocco: "",
  Moroni: "EAT",
  Mosca: "MSK",
  Mossul: "",
  Mozambico: "CAT",
  "Muang Phonsavan": "",
  Mudanjiang: "CST",
  "Monaco di Baviera": "CET",
  Multan: "PKT",
  Mumbai: "IST",
  Munich: "CET",
  Murcia: "CET",
  Muscat: "",
  Mwanza: "EAT",
  Birmania: "",
  Mykolayiv: "EET",
  Mysore: "IST",
  "N'Djamena": "WAT",
  "Naberezhnyye Chelny": "MSK",
  Nagasaki: "JST",
  Nagoya: "JST",
  Nagpur: "IST",
  Nairobi: "EAT",
  Namangan: "",
  Namibia: "CAT",
  "Namp'o": "KST",
  Nampula: "CAT",
  Nanchang: "CST",
  Nanchong: "CST",
  Nangi: "IST",
  Nanchino: "CST",
  Nanning: "CST",
  Nantong: "CST",
  Napoli: "CET",
  Nashville: "CST",
  Nasik: "IST",
  Nassau: "EST",
  Natal: "",
  "Naucalpan de Juarez": "CST",
  Nauru: "",
  "Nay Pyi Taw": "",
  Ndola: "CAT",
  "Nebraska - Omaha": "CST",
  Neijiang: "CST",
  Nellore: "IST",
  Nepal: "",
  Nerima: "JST",
  "Paesi Bassi": "CET",
  "Netherlands Antilles": "AST",
  "Nuova Caledonia": "",
  "Nuova Delhi": "IST",
  "New Hampshire": "EST",
  Newark: "EST",
  "New Kingston": "EST",
  "New South Memphis": "CST",
  "New York": "EST",
  "Nuova Zelanda": "NZDT",
  Niamey: "WAT",
  Nicaragua: "CST",
  Nicosia: "EET",
  Niger: "WAT",
  Nigeria: "WAT",
  Niigata: "JST",
  Ningbo: "CST",
  Nishinomiya: "JST",
  Niterói: "",
  Niue: "",
  "Nizhniy Novgorod": "MSK",
  "Nizhniy Tagil": "",
  "Isola Norfolk": "",
  "North Carolina": "EST",
  "Corea del Nord": "KST",
  "North York": "EST",
  "Marianne Settentrionali, isole": "ChST",
  Norvegia: "CET",
  Nouakchott: "GMT",
  Noumea: "",
  "Nova Iguaçu": "",
  Novokuzneck: "",
  Novosibirsk: "",
  Norimberga: "CET",
  "Nuku'alofa": "",
  "Nuuk (Godthåb)": "",
  Oakland: "PST",
  Odessa: "EET",
  Oita: "JST",
  Okayama: "JST",
  Okene: "WAT",
  "Oklahoma City": "CST",
  Omaha: "CST",
  Oman: "",
  Omdurman: "CAT",
  Omsk: "",
  Onitsha: "WAT",
  Orano: "CET",
  Oranjestad: "AST",
  Orenburg: "",
  Orumiyeh: "",
  Osaka: "JST",
  Osasco: "",
  Oslo: "CET",
  Ottawa: "EST",
  Ouagadougou: "GMT",
  Oujda: "",
  Owensboro: "CST",
  Oyo: "WAT",
  Padang: "WIB",
  Pakistan: "PKT",
  Palau: "",
  Palembang: "WIB",
  Palermo: "CET",
  Palestina: "EET",
  Palikir: "",
  "Palma di Maiorca": "CET",
  Panamá: "EST",
  Panihati: "IST",
  Panshan: "CST",
  Panzhihua: "CST",
  Papeete: "",
  "Papua Nuova Guinea": "",
  Paraguay: "",
  Paramaribo: "",
  Parigi: "CET",
  Pasto: "",
  Patna: "IST",
  Filadelfia: "EST",
  Pensacola: "CST",
  Penza: "MSK",
  Pereira: "",
  "Perm'": "",
  Perth: "AWST",
  Perù: "",
  Peshawar: "PKT",
  "Petaling Jaya": "",
  Filippine: "PST",
  "Phnom Penh": "",
  Pietermaritzburg: "SAST",
  Pikine: "GMT",
  Pimpri: "IST",
  Pingdingshan: "CST",
  Pingxiang: "CST",
  Pitcairn: "",
  Plymouth: "AST",
  Podgorica: "CET",
  "Pointe-Noire": "WAT",
  Polonia: "CET",
  Ponce: "AST",
  Pontianak: "WIB",
  "Port Elizabeth": "SAST",
  "Port Harcourt": "WAT",
  "Port Louis": "",
  "Port Moresby": "",
  "Porto Sudan": "CAT",
  "Port Vila": "",
  "Port-au-Prince": "EST",
  "Port of Spain": "AST",
  "Porto Alegre": "",
  "Porto-Novo": "WAT",
  Portogallo: "WET",
  Poznan: "CET",
  Praga: "CET",
  Praia: "",
  Pretoria: "SAST",
  Prishtina: "CET",
  Providence: "EST",
  "Puch'on": "KST",
  Puebla: "CST",
  "Puerto Rico": "AST",
  poona: "IST",
  Pusan: "KST",
  Putian: "CST",
  Pyongyang: "KST",
  Qaraghandy: "",
  Qatar: "",
  Qingdao: "CST",
  Qinhuangdao: "CST",
  Qiqihar: "CST",
  Qom: "",
  Quebec: "EST",
  "Quebec City": "EST",
  Queretaro: "CST",
  Quetta: "PKT",
  Quilmes: "",
  Quilon: "IST",
  Quito: "",
  "Ra's Bayrut": "EET",
  Rabat: "",
  Raipur: "IST",
  Rajkot: "IST",
  Rajshahi: "",
  Ranchi: "IST",
  Rangoon: "",
  "Rapid City": "MST",
  Rasht: "",
  Rawalpindi: "PKT",
  Recife: "",
  Regina: "CST",
  Resistencia: "",
  Réunion: "",
  Reykjavík: "GMT",
  Reynosa: "CST",
  "Ribeirao Preto": "",
  "Ribeirao das Neves": "",
  Riga: "EET",
  "Rio de Janeiro": "",
  Riyad: "",
  "Road Town": "AST",
  Roma: "CET",
  Romania: "EET",
  Rome: "CET",
  Rosario: "",
  Roseau: "AST",
  "Rostov sul Don": "MSK",
  Rotterdam: "CET",
  "Russia - Moscow": "MSK",
  Ruanda: "CAT",
  "Ryazan'": "MSK",
  Sacramento: "PST",
  Sagamihara: "JST",
  Saharanpur: "IST",
  "San Bartolomeo": "AST",
  "St. George's": "AST",
  "Sant’Elena": "GMT",
  "Saint Helier": "GMT",
  "Saint John's": "AST",
  "Saint Kitts e Nevis": "AST",
  "Saint Louis": "CST",
  "Santa Lucia": "AST",
  "Saint Martin": "AST",
  "Saint Peter Port": "GMT",
  "San Pietroburgo": "MSK",
  "Saint Pierre e Miquelon": "",
  "Saint Vincent e Grenadine": "AST",
  "Saint-Denis": "",
  "Saint-Pierre": "",
  Saitama: "JST",
  Sakai: "JST",
  Salem: "IST",
  "Salt Lake City": "MST",
  Salta: "",
  Saltillo: "CST",
  Salvador: "",
  Salzburg: "CET",
  Samara: "",
  Samoa: "",
  Samsun: "",
  "Samut Prakan": "",
  "San Antonio": "CST",
  "San Diego": "PST",
  "San Jose": "PST",
  "San Luis Potosí": "CST",
  "San Marino": "CET",
  "San Miguel de Tucumán": "",
  "San Nicolas de los Garzas": "CST",
  "San Pedro Sula": "CST",
  "San Salvador": "CST",
  "San'a": "",
  Sandakan: "",
  Edessa: "",
  "Santa Cruz de la Sierra": "",
  "Santa Fe": "",
  "Santa Marta": "",
  "Santiago del Cile": "",
  "Santiago di Cuba": "CST",
  "Santiago de los Caballeros": "AST",
  "Santo Andre": "",
  "Santo Domingo": "AST",
  Santos: "",
  "São Bernardo do Campo": "",
  "Sao Joao de Meriti": "",
  "Sao Jose do Rio Preto": "",
  "Sao Jose dos Campos": "",
  "São Luís": "",
  "San Paolo": "",
  "São Tomé": "GMT",
  "São Tomé e Príncipe": "GMT",
  Sapporo: "JST",
  Sarajevo: "CET",
  Saratov: "",
  Sargodha: "PKT",
  Saskatchewan: "CST",
  "Arabia Saudita": "",
  Seattle: "PST",
  Semarang: "WIB",
  Sendai: "JST",
  Senegal: "GMT",
  Seul: "KST",
  Serbia: "CET",
  Seremban: "",
  Serra: "",
  Sebastopoli: "MSK",
  Siviglia: "CET",
  Seychelles: "",
  "Shah Alam": "",
  Shanghai: "CST",
  Shantou: "CST",
  Shaoguan: "CST",
  Shaoxing: "CST",
  Sharja: "",
  Shashi: "CST",
  Sheffield: "GMT",
  Shenyang: "CST",
  Shenzhen: "CST",
  Shihezi: "",
  Shijiazhuang: "CST",
  Shiliguri: "IST",
  Shimminatocho: "JST",
  Shiraz: "",
  "Shivaji Nagar": "IST",
  Shizuoka: "JST",
  Shuangyashan: "CST",
  Şımkent: "",
  Sialkot: "PKT",
  "Sierra Leone": "GMT",
  Singapore: "",
  "Sioux Falls": "CST",
  Siping: "CST",
  Situbondo: "WIB",
  Skopje: "CET",
  Slovacchia: "CET",
  Slovenia: "CET",
  Sofia: "EET",
  Sokoto: "WAT",
  Solapur: "IST",
  "Isole Salomone": "",
  Somalia: "EAT",
  Songnam: "KST",
  Sorocaba: "",
  Sudafrica: "SAST",
  "South Boston": "EST",
  "South Dakota - Rapid City": "MST",
  "South Dakota - Sioux Falls": "CST",
  "Georgia del Sud e isole Sandwich meridionali": "",
  "Corea del Sud": "KST",
  Soweto: "SAST",
  Spagna: "CET",
  "Sri Lanka": "",
  Srinagar: "IST",
  "St. John's": "NST",
  "Port Stanley": "",
  Stoccolma: "CET",
  Strasbourg: "CET",
  Stoccarda: "CET",
  Sucre: "",
  Sudan: "CAT",
  Suez: "EET",
  Sukkur: "PKT",
  Sultanah: "",
  Surabaya: "WIB",
  Surakarta: "WIB",
  Surat: "IST",
  Suriname: "",
  Suva: "",
  Suwon: "KST",
  Suzhou: "CST",
  "Svalbard e Jan Mayen": "CET",
  Swaziland: "SAST",
  Svezia: "CET",
  Svizzera: "CET",
  Sydney: "AEDT",
  Siria: "EET",
  Stettino: "CET",
  "T'ai-chung-shih": "CST",
  "Ta`izz": "",
  Tabriz: "",
  Tabuk: "",
  Taegu: "KST",
  Daejeon: "KST",
  "Tai'an": "CST",
  "Tainan City": "CST",
  Taipei: "CST",
  Taiwan: "CST",
  Taiyuan: "CST",
  Taizhou: "CST",
  Tagikistan: "",
  Tallinn: "EET",
  Tangerang: "WIB",
  Tanggu: "CST",
  Tangeri: "",
  Tangshan: "CST",
  "Tanjungkarang-Telukbetung": "WIB",
  Tanta: "EET",
  Tanzania: "EAT",
  Taskent: "",
  Tbilisi: "",
  Tegucigalpa: "CST",
  Teheran: "",
  "Tel Aviv-Yafo": "IST",
  Tembisa: "SAST",
  Teni: "IST",
  "Tennessee - Knoxville": "EST",
  Teresina: "",
  Thailandia: "",
  Thane: "IST",
  "Ho Chi Minh": "",
  "The Valley": "AST",
  Thimphu: "",
  Thiruvananthapuram: "IST",
  Tianjin: "CST",
  Tijuana: "PST",
  Tirana: "CET",
  Tiruchchirappalli: "IST",
  Tirunelveli: "IST",
  Tiruppur: "IST",
  Tlalnepantla: "CST",
  Tlaquepaque: "CST",
  Togo: "GMT",
  Tokelau: "",
  Tokyo: "JST",
  Togliattigrad: "",
  Toluca: "CST",
  Tomsk: "",
  Tonala: "CST",
  Tonga: "",
  Torino: "CET",
  Toronto: "EST",
  Torreón: "CST",
  Tórshavn: "WET",
  Tolosa: "CET",
  Toyohashi: "JST",
  Toyonaka: "JST",
  "Trinidad e Tobago": "AST",
  Tripoli: "EET",
  Trujillo: "",
  Tucson: "MST",
  Tula: "MSK",
  Tulsa: "CST",
  Tulum: "EST",
  Tunisi: "CET",
  Tunisia: "CET",
  Turchia: "",
  Turkmenistan: "",
  "Isole Turks e Caicos": "EST",
  Tuvalu: "",
  "Tuxtla Gutiérrez": "CST",
  "Tver'": "MSK",
  "Tjumen'": "",
  "Isole Vergini Americane": "AST",
  Uberlandia: "",
  Udaipur: "IST",
  Ufa: "",
  Uganda: "EAT",
  Uijongbu: "KST",
  Ujjain: "IST",
  Ucraina: "EET",
  "Ul'janovsk": "",
  "Ulan Bator": "",
  Ulhasnagar: "IST",
  Ulsan: "KST",
  "Emirati Arabi Uniti": "",
  "Regno Unito": "GMT",
  Uruguay: "",
  Ürümqi: "",
  Utsunomiya: "JST",
  Uzbekistan: "",
  Vadodara: "IST",
  Vaduz: "CET",
  "La Valletta": "CET",
  Van: "",
  Vancouver: "PST",
  Vanuatu: "",
  Vaticano: "CET",
  "Città del Vaticano": "CET",
  Venezuela: "",
  Venice: "CET",
  Veracruz: "CST",
  Vereeniging: "SAST",
  Vermont: "EST",
  Victoria: "",
  Vienna: "CET",
  Vientiane: "",
  Vietnam: "",
  Vijayawada: "IST",
  "Vila Velha": "",
  "Villa Nueva": "CST",
  Vilnius: "EET",
  Virginia: "EST",
  "Virginia Beach": "EST",
  Vishakhapatnam: "IST",
  Vladivostok: "",
  Volgograd: "",
  Voronezh: "MSK",
  "Wallis e Futuna": "",
  Warangal: "IST",
  Warri: "WAT",
  Varsavia: "CET",
  Washington: "EST",
  Weifang: "CST",
  Welkom: "SAST",
  Wellington: "NZDT",
  Wenzhou: "CST",
  "Sahara Occidentale": "",
  Whitehorse: "PST",
  Wichita: "CST",
  Willemstad: "AST",
  Wilmington: "EST",
  Windhoek: "CAT",
  Winnipeg: "CST",
  Breslavia: "CET",
  Wuhan: "CST",
  Wuhu: "CST",
  Wuxi: "CST",
  "Xi'an": "CST",
  Xiamen: "CST",
  Xiangfan: "CST",
  Xiangtan: "CST",
  Xianyang: "CST",
  Xingtai: "CST",
  Xining: "CST",
  Xinpu: "CST",
  Xinxiang: "CST",
  Xinyang: "CST",
  Xuanhua: "CST",
  Xuchang: "CST",
  Xuzhou: "CST",
  Yamoussoukro: "GMT",
  Yancheng: "CST",
  Yangjiang: "CST",
  Yangquan: "CST",
  Yangzhou: "CST",
  Yantai: "CST",
  Yaoundé: "WAT",
  "Jaroslavl'": "MSK",
  Yazd: "",
  Ekaterinburg: "",
  Yellowknife: "MST",
  Yemen: "",
  Jerevan: "",
  Yichang: "CST",
  Yinchuan: "CST",
  Yingkou: "CST",
  Yogyakarta: "WIB",
  Yokohama: "JST",
  Yokosuka: "JST",
  Yono: "JST",
  Yunfu: "CST",
  Zagabria: "CET",
  "Zagreb - Centar": "CET",
  Zahedan: "",
  Zambia: "CAT",
  Zamboanga: "PST",
  Zanzibar: "EAT",
  Zapopan: "CST",
  Zaporizhzhya: "EET",
  Saragozza: "CET",
  Zaria: "WAT",
  Zhangjiakou: "CST",
  Zhangzhou: "CST",
  Zhanjiang: "CST",
  Zhengzhou: "CST",
  Zhenjiang: "CST",
  Zhoukou: "CST",
  Zhuhai: "CST",
  Zhumadian: "CST",
  Zhuzhou: "CST",
  Zibo: "CST",
  Zigong: "CST",
  Zimbabwe: "CAT",
  Zunyi: "CST",
  Zurich: "CET",
  Aden: "",
  "vina causino": ""
};
